### ISSUE TITLE
Filtering an empty event results in a NullPointerException

### ISSUE THREAD

**Issue by WouterHadrian** [knative-sandbox/eventing-kafka-broker#1455]
**Describe the bug**
By accident, I created a service that triggers on an event and sends back a cloudevent with an empty/null data part. This results in an unhandeled exception in the kafka-broker-dispatcher, in the AttributesFilter part (see stack trace below). The polling part crashes and all triggers in the system are not fired anymore. 

 **Expected behavior**
* being able to send a cloudevent with no/null data part
* Even If the filtering part crashes, the main loop should continue as expected. 

 **To Reproduce**

* setup a simple trigger with a filter (I used a filter only on the type)
* send an cloudevent with an null/empty data part to the broker

 **Knative release version**
v1.0.0

 **Additional context**

Stack trace:
```
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  SEVERE: Unhandled exception
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  java.lang.NullPointerException
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.filter.AttributesFilter.test(AttributesFilter.java:91)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.filter.AttributesFilter.test(AttributesFilter.java:33)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.lambda$onRecordReceived$1(RecordDispatcherImpl.java:145)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.core.impl.future.SucceededFuture.onSuccess(SucceededFuture.java:64)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.onRecordReceived(RecordDispatcherImpl.java:143)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.dispatch(RecordDispatcherImpl.java:117)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherMutatorChain.dispatch(RecordDispatcherMutatorChain.java:58)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.UnorderedConsumerVerticle.lambda$startConsumer$0(UnorderedConsumerVerticle.java:35)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.kafka.client.consumer.impl.KafkaConsumerImpl.lambda$handler$1(KafkaConsumerImpl.java:81)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.run(KafkaReadStreamImpl.java:237)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$schedule$8(KafkaReadStreamImpl.java:192)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  	at java.base/java.lang.Thread.run(Unknown Source)
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  
[kafka-broker-dispatcher-6797b9575-nc72f kafka-broker-dispatcher]  {"@timestamp":"2021-11-10T09:01:14.035Z","@version":"1","message":"[Consumer clientId=consumer-b1821e69-87c3-447f-9f5c-f284bf2167bc-1, groupId=b1821e69-87c3-447f-9f5c-f284bf2167bc] Member consumer-b1821e69-87c3-447f-9f5c-f284bf2167bc-1-02a363cc-0c52-42dd-9ea3-1aaff0bbaee3 sending LeaveGroup request to coordinator lazy-kafka-0.lazy-kafka-headless.default.svc.cluster.local:9092 (id: 2147483647 rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.","logger_name":"org.apache.kafka.clients.consumer.internals.AbstractCoordinator","thread_name":"kafka-coordinator-heartbeat-thread | b1821e69-87c3-447f-9f5c-f284bf2167bc","level":"INFO","level_value":20000}
```

**Comment by WouterHadrian** [comment]
Yeah, it is a really simple trigger:

```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-myScript
spec:
  broker: default
  filter:
    attributes:
      type: io.events.myEvent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: script-myScript
```
