### ISSUE TITLE
Support transactions

### ISSUE THREAD

**Issue by joke** [knative-sandbox/eventing-kafka-broker#1530]
**Problem**
Kafka has support for idempotence and transactions. This is specially useful to prevent duplicated events in case of connection errors.

Enabling this option in the config map `config-kafka-sink-data-plane` under `config-kafka-sink-producer.properties` causes sending errors because no transaction is initialized. The producer could initialize a transaction if `enable.idempotence` is enabled.

```yaml
enable.idempotence=true
ransaction.timeout.ms=120000
transactional.id=my-identifier
```

```JSON
{"@timestamp":"2021-11-23T09:40:20.256Z","@version":"1","message":"Failed to send record topic=my_topic {}","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.handler.IngressRequestHandlerImpl","thread_name":"vert.x-eventloop-thread-0","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalStateException: Cannot perform a 'send' before completing a call to initTransactions when transactions are enabled.\n\tat org.apache.kafka.clients.producer.internals.TransactionManager.failIfNotReadyForSend(TransactionManager.java:433)\n\tat org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:949)\n\tat org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:886)\n\tat io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$send$4(KafkaWriteStreamImpl.java:76)\n\tat io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)\n\tat io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)\n\tat io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)\n\tat io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n","topic":"my_topic"}
```

```
java.lang.IllegalStateException: Cannot perform a 'send' before completing a call to initTransactions when transactions are enabled.
	at org.apache.kafka.clients.producer.internals.TransactionManager.failIfNotReadyForSend(TransactionManager.java:433)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:949)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:886)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$send$4(KafkaWriteStreamImpl.java:76)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** Event producer

**Exit Criteria**
Messages are send if `enable.idempotence=true`.

**Comment by pierDipi** [comment]
Hi @joke !

when `enable.idempotence=true` it does work, are you trying to set `transaction.*` configs too?

**Comment by joke** [comment]
@pierDipi
I did specify these settings causing the exception above:

```yaml
enable.idempotence=true
ransaction.timeout.ms=120000
transactional.id=my-identifier
```

**Comment by pierDipi** [comment]
@joke I was reading your Exist criteria:

> Exit Criteria
Messages are send if enable.idempotence=true.

For that reason, I'm not sure if you specifically want transaction support so that you can read events with a consumer that has the isolation level set to read committed (I need to think about this if that makes sense in our context) or just use an idempotent producer.
Because `enable.idempotence=true` already works.

**Comment by joke** [comment]
@pierDipi you are absolutely right. I mixed those two up. In my case I want the idempotence. You're right settings `enable.idempotence=true` works.

**Comment by pierDipi** [comment]
> In my case I want the idempotence.

Ok, then you can just keep these 2 configs commented:
```properties
# transaction.timeout.ms=120000
# transactional.id=my-identifier
```
and set
```properties
enable.idempotence=true
```
as I tried in https://github.com/knative-sandbox/eventing-kafka-broker/pull/1531/files

@joke, thanks for reporting, I'm closing this, for now.

**Comment by joke** [comment]
@pierDipi thank you very much.
