### ISSUE TITLE
Dispatcher pod logs unhandled exception during event consumption 

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka-broker#2176]
**Describe the bug**
```

May 10, 2022 9:10:42 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException: Cannot invoke "dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager$OffsetTracker.recordNewOffset(long)" because the return value of "java.util.Map.get(Object)" is null
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager.commit(OffsetManager.java:133)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager.successfullySentToSubscriber(OffsetManager.java:103)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.onSubscriberSuccess(RecordDispatcherImpl.java:246)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.lambda$onFilterMatching$1(RecordDispatcherImpl.java:227)
	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.lambda$null$4(CircuitBreakerImpl.java:232)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

 **Expected behavior**
This exception should not happen and when it happens, event consumption is halted. 

 **To Reproduce**
Send large amount of events to topic and and this should re-occur

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment]
/assign

Fix in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2179
