### ISSUE TITLE
Dispatcher begins from oldest offset after rebalance

### ISSUE THREAD

**Issue by apenen** [knative-sandbox/eventing-kafka-broker#2201]
**Describe the bug**
Sometimes one of our kafka dispatchers begins from oldest offset after topic rebalance.

We see that when the dispatchers have problems sending events to a subscriber with 504 errors. The first dispatcher that gives problems with the poll() causes the rebalancing of the affected consumer group. Once the consumer group is recovered, the offset of the dispatcher that started the rebalancing sometimes starts with the oldest available offset, even seeing in the traces that kafka indicates the correct offset.

![image](https://user-images.githubusercontent.com/9284027/168566809-10aca650-6a54-4419-a224-0dc225135f7c.png)
![image](https://user-images.githubusercontent.com/9284027/168566936-ffb4bdc6-6ff0-486d-949d-ef8d5798539a.png)

 **Expected behavior**
No offset "reset".

 **To Reproduce**
We have 12 dispatchers, topics with 12 partitions and 58 consumer groups (triggers). By forcing 504 errors on one trigger and after consumer group rebalancing the offset can start from the oldest available.

 **Knative release version**
knative eventing 1.2.0
eventing-kafka-broker 1.2.3

 **Additional context**
None

**Comment by aslom** [comment]
@steven0711dong is that related to re-balancing problems you noticed?

**Comment by German-Michelena** [comment]
We also have this problem. We see this exception from the dispatcher before losing the offset.

  ```
      "@timestamp": "2022-06-07T05:16:23.102Z",
        "@version": "1",
        "message": "Exception occurred, discarding the record topic=knative-broker-tienda-default partition=3 offset=52262495",
        "logger_name": "dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl",
        "thread_name": "vert.x-eventloop-thread-0",
        "level": "ERROR",
        "level_value": 40000,
        "stack_trace": "java.lang.IndexOutOfBoundsException: bitIndex < 0: -999879
                        at java.base/java.util.BitSet.set(Unknown Source)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager$OffsetTracker.recordNewOffset(OffsetManager.java:211)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager.commit(OffsetManager.java:118)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.OffsetManager.recordDiscarded(OffsetManager.java:112)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.onFilterNotMatching(RecordDispatcherImpl.java:179)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.onRecordReceived(RecordDispatcherImpl.java:165)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherImpl.dispatch(RecordDispatcherImpl.java:123)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherMutatorChain.dispatch(RecordDispatcherMutatorChain.java:58)
                        at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.UnorderedConsumerVerticle.handleRecords(UnorderedConsumerVerticle.java:86)
                        at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
                        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
                        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
                        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
                        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
                        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
                        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
                        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
                        at io.vertx.kafka.client.consumer.impl.KafkaConsumerImpl.lambda$poll$16(KafkaConsumerImpl.java:685)
                        at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$null$41(KafkaReadStreamImpl.java:875)
                        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
                        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
                        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
                        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
                        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
                        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
                        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                        at java.base/java.lang.Thread.run(Unknown Source)
",
        "topic": "knative-broker-tienda-default",
        "partition": 3,
        "offset": 52262495
    }
```

**Comment by pierDipi** [comment]
@German-Michelena can you share the Knative version?

**Comment by German-Michelena** [comment]
> @German-Michelena can you share the Knative version you're using?

@pierDipi , Knative version 1.2.0

**Comment by apenen** [comment]
Hi!

Any news?

**Comment by pierDipi** [comment]
Are you still seeing this in a more recent version?

I've never managed to reproduce this issue.

**Comment by pierDipi** [comment]
If you can share a reproducer that would be great!

**Comment by German-Michelena** [comment]
Hi, we still have this issue (knative 1.2.0 in a GKE cluster, v1.21.14-gke.2700). When the nodepool was upgraded and some nodes where restarted, the dispatcher lost the offset, and started again from the beginning:

![image](https://user-images.githubusercontent.com/57520699/197198739-2ad0449b-51f5-4cc4-a504-feb23f5d7006.png)

We manually modified the offset to the previous value, so that all those message wouldn't be resent (that is the cause for the sudden drop in the lag)

**Comment by jtucci** [comment]
I'm also seeing this same problem on v1.5.8

**Comment by apenen** [comment]
> Are you still seeing this in a more recent version like 1.8?
> 
> I've never managed to reproduce this issue.

Currently we can't upgrade production version...

**Comment by apenen** [comment]
Not happening in version 1.9
