### ISSUE TITLE
Thread blocked

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka-broker#371]
**Describe the bug**

https://github.com/knative-sandbox/eventing-kafka-broker/pull/364/checks?check_run_id=1333585414

```
  Oct 30, 2020 7:10:45 PM io.vertx.core.impl.BlockedThreadChecker
  WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6335 ms, time limit is 2000 ms
  io.vertx.core.VertxException: Thread blocked
  	at java.base@14.0.2/java.lang.Class.getDeclaredMethods0(Native Method)
  	at java.base@14.0.2/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
  	at java.base@14.0.2/java.lang.Class.getDeclaredMethods(Unknown Source)
  	at app//com.fasterxml.jackson.databind.util.ClassUtil.getDeclaredMethods(ClassUtil.java:1120)
  	at app//com.fasterxml.jackson.databind.util.ClassUtil.getClassMethods(ClassUtil.java:1143)
  	at app//com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._addMemberMethods(AnnotatedMethodCollector.java:110)
  	at app//com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collect(AnnotatedMethodCollector.java:47)
  	at app//com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collectMethods(AnnotatedMethodCollector.java:33)
  	at app//com.fasterxml.jackson.databind.introspect.AnnotatedClass._methods(AnnotatedClass.java:365)
  	at app//com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:305)
  	at app//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:525)
  	at app//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:309)
  	at app//com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:196)
  	at app//com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:252)
  	at app//com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:346)
  	at app//com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:216)
  	at app//com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
  	at app//com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1388)
  	at app//com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1356)
  	at app//com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:551)
  	at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:343)
  	at app//com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:174)
  	at app//com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1366)
  	at app//com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:551)
  	at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:343)
  	at app//com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:174)
  	at app//com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1366)
  	at app//com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:551)
  	at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:343)
  	at app//com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:174)
  	at app//com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1366)
  	at app//com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:551)
  	at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:343)
  	at app//com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:197)
  	at app//com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1346)
  	at app//com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:510)
  	at app//com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:713)
  	at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
  	at app//com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2795)
  	at app//com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
  	at app//net.logstash.logback.marker.ObjectAppendingMarker.writeFieldValue(ObjectAppendingMarker.java:94)
  	at app//net.logstash.logback.marker.SingleFieldAppendingMarker.writeTo(SingleFieldAppendingMarker.java:84)
  	at app//net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:76)
  	at app//net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:43)
  	at app//net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:77)
  	at app//net.logstash.logback.composite.CompositeJsonFormatter.writeEventToGenerator(CompositeJsonFormatter.java:193)
  	at app//net.logstash.logback.composite.CompositeJsonFormatter.writeEventToOutputStream(CompositeJsonFormatter.java:170)
  	at app//net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:122)
  	at app//net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:34)
  	at app//ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
  	at app//ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
  	at app//ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
  	at app//ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
  	at app//ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
  	at app//ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
  	at app//ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
  	at app//ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
  	at app//ch.qos.logback.classic.Logger.info(Logger.java:583)
  	at app//dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerMessageHandler.lambda$handle$0(ResourcesReconcilerMessageHandler.java:31)
  	at app//dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerMessageHandler$$Lambda$238/0x0000000100397440.handle(Unknown Source)
  	at app//io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
  	at app//io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:61)
  	at app//io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:165)
  	at app//io.vertx.core.impl.future.FutureImpl.onSuccess(FutureImpl.java:88)
  	at app//dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerMessageHandler.handle(ResourcesReconcilerMessageHandler.java:31)
  	at app//dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerMessageHandler.handle(ResourcesReconcilerMessageHandler.java:14)
  	at app//io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52)
  	at app//io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:189)
  	at app//io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
  	at app//io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:164)
  	at app//io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:130)
  	at app//io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:106)
  	at app//io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
  	at app//io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
  	at app//io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:56)
  	at app//io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$189/0x0000000100336040.run(Unknown Source)
  	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
  	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
  	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base@14.0.2/java.lang.Thread.run(Unknown Source)
```

 **Expected behavior**

No thread blocked error.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**
`devel`

 **Additional context**

/area data-plane

**Comment by pierDipi** [comment]
cc @slinkydeveloper

**Comment by slinkydeveloper** [comment]
Here we go! /assign

**Comment by slinkydeveloper** [comment]
It's the logging! :smile:
