### ISSUE TITLE
Running the data plane unit tests in the IDE fails

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#629]
**Describe the bug**
Running the data plane unit tests in the IDE (or just using mvn test on my local machine fails)

 **Expected behavior**
Unit tests should not fail

**Comment by pierDipi** [comment]
Can you explain why? GH actions have no k8s running and they run fine.

**Comment by slinkydeveloper** [comment]
I have this problem on my machine:

```
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.879 s <<< FAILURE! - in dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest
[ERROR] dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.getCredentialsFromSecret(Vertx,VertxTestContext)  Time elapsed: 0.763 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Secret]  with name: [null]  in namespace: [my-secret-namespace]  failed.
        at dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.getCredentialsFromSecret(KubernetesAuthProviderTest.java:74)
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:44943
        at dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.getCredentialsFromSecret(KubernetesAuthProviderTest.java:74)
Caused by: java.net.ConnectException: Connessione rifiutata
        at dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.getCredentialsFromSecret(KubernetesAuthProviderTest.java:74)

[ERROR] dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.shouldFailOnInvalidSecret(Vertx,VertxTestContext)  Time elapsed: 0.065 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Secret]  with name: [null]  in namespace: [my-secret-namespace]  failed.
        at dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.shouldFailOnInvalidSecret(KubernetesAuthProviderTest.java:130)
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:50167
        at dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.shouldFailOnInvalidSecret(KubernetesAuthProviderTest.java:130)
Caused by: java.net.ConnectException: Connessione rifiutata
        at dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProviderTest.shouldFailOnInvalidSecret(KubernetesAuthProviderTest.java:130)

```

**Comment by slinkydeveloper** [comment]
Does it fail on yours too?

**Comment by pierDipi** [comment]
We use the mock-server for UTs

**Comment by pierDipi** [comment]
Does it happen on master?

**Comment by slinkydeveloper** [comment]
Yes it does. I just checked that i don't have kubernetes up and running, just to be 100% sure

**Comment by pierDipi** [comment]
Can you try with using `./test/presubmit-tests.sh --unit-tests`?

**Comment by slinkydeveloper** [comment]
Using the script works, but using the IDE nor `mvn test` on local machine doesn't.

**Comment by pierDipi** [comment]
It works on my machine, I use the wrapper `./mvnw clean test`, do you have Java 15 installed?

**Comment by slinkydeveloper** [comment]
```
(master) [1] % java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment 20.9 (build 15.0.2+7)
OpenJDK 64-Bit Server VM 20.9 (build 15.0.2+7, mixed mode, sharing)
```

**Comment by slinkydeveloper** [comment]
The wrapper shouldn't change anything, I have maven installed in my `$PATH`

**Comment by pierDipi** [comment]
There must be something wrong in your local setup :thinking:

**Comment by slinkydeveloper** [comment]
I'll try to figure it out, meanwhile i keep it open, just in case somebody notices the same problem
