### ISSUE TITLE
Race on running DataPlaneTest inside my IDE

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka-broker#995]
**Describe the bug**

Getting a race, when running the `DataPlaneTest` inside of my development IDE:

```
16:41:45.783 [vert.x-eventloop-thread-4] ERROR dev.knative.eventing.kafka.broker.dispatcher.consumer.impl.UnorderedOffsetManager - failed to commit for topic partition knative-eventing-42-kafka-broker-42 3 offset 1
org.apache.kafka.common.errors.WakeupException: null
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:514)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:278)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:1005)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1495)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1443)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$commit$29(KafkaReadStreamImpl.java:611)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$submitTaskWhenStarted$3(KafkaReadStreamImpl.java:135)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
16:41:45.784 [vert.x-kafka-consumer-thread-0] ERROR dev.knative.eventing.kafka.broker.dispatcher.consumer.impl.BaseConsumerVerticle - Consumer exception
org.apache.kafka.common.errors.WakeupException: null
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeTriggerWakeup(ConsumerNetworkClient.java:514)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:278)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:1005)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1495)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1443)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$commit$29(KafkaReadStreamImpl.java:611)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$submitTaskWhenStarted$3(KafkaReadStreamImpl.java:135)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
16:41:45.806 [vert.x-eventloop-thread-5] ERROR io.vertx.core.http.impl.HttpClientRequestImpl - io.vertx.core.VertxException: Connection was closed
16:41:45.808 [vert.x-eventloop-thread-5] ERROR dev.knative.eventing.kafka.broker.dispatcher.RecordDispatcher - Failed to send event to subscriber topic=knative-eventing-42-kafka-broker-42 partition=5 headers=[KafkaHeaderImpl{'ce_specversion': 0.3}, KafkaHeaderImpl{'ce_id': cf6ebb2c-34f9-4997-bb2d-226dade3baf1}, KafkaHeaderImpl{'ce_source': /api/rossi}, KafkaHeaderImpl{'ce_type': type-ce-2}, KafkaHeaderImpl{'ce_schemaurl': /api/data-schema-ce-2}, KafkaHeaderImpl{'ce_subject': subject-ce-2}] offset=0 event=CloudEvent{id='cf6ebb2c-34f9-4997-bb2d-226dade3baf1', source=/api/rossi, type='type-ce-2', schemaurl=/api/data-schema-ce-2, subject='subject-ce-2', data=BytesCloudEventData{value=[100, 97, 116, 97, 45, 99, 101, 45, 50]}, extensions={}}
io.vertx.core.VertxException: Connection was closed
16:41:45.808 [vert.x-eventloop-thread-5] ERROR dev.knative.eventing.kafka.broker.dispatcher.RecordDispatcher - Failed to send event to dead letter queue topic=knative-eventing-42-kafka-broker-42 partition=5 headers=[KafkaHeaderImpl{'ce_specversion': 0.3}, KafkaHeaderImpl{'ce_id': cf6ebb2c-34f9-4997-bb2d-226dade3baf1}, KafkaHeaderImpl{'ce_source': /api/rossi}, KafkaHeaderImpl{'ce_type': type-ce-2}, KafkaHeaderImpl{'ce_schemaurl': /api/data-schema-ce-2}, KafkaHeaderImpl{'ce_subject': subject-ce-2}] offset=0 event=CloudEvent{id='cf6ebb2c-34f9-4997-bb2d-226dade3baf1', source=/api/rossi, type='type-ce-2', schemaurl=/api/data-schema-ce-2, subject='subject-ce-2', data=BytesCloudEventData{value=[100, 97, 116, 97, 45, 99, 101, 45, 50]}, extensions={}}
io.vertx.core.impl.NoStackTraceThrowable: No DLQ set
```

**Comment by slinkydeveloper** [comment]
Looking from where we call `wakeup()` inside `vertx-kafka-client`, It seems to me the problem is that the test terminates before the offset of the final message is committed.

I suggest that before terminating the test, we should wait for the offset to be committed (using awaitability should do the trick)
